/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/invites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Pending Invites */
        get: operations["list_pending_invites_invites_get"];
        put?: never;
        /** Send Invite */
        post: operations["send_invite_invites_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/invites/{external_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke Invite */
        delete: operations["revoke_invite_invites__external_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/invites/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accept Invite Route */
        post: operations["accept_invite_route_invites_accept_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Forgot Password */
        post: operations["forgot_password_auth_forgot_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Reset Password Target */
        get: operations["reset_password_target_auth_reset_password_get"];
        put?: never;
        /** Reset Password Route */
        post: operations["reset_password_route_auth_reset_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Applications */
        get: operations["list_applications_applications_get"];
        put?: never;
        /** Create Application */
        post: operations["create_application_applications_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/{external_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Application */
        get: operations["get_application_applications__external_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Application
         * @description Soft delete only (AD-15 disclosed scope) — child rows (discovery_run,
         *     journey, page, ...) and the Vault secret are deliberately left behind;
         *     nothing purges them yet. Blocked while discovery is running so a live
         *     crawler doesn't keep writing rows for an application that just
         *     disappeared from Home.
         */
        delete: operations["delete_application_applications__external_id__delete"];
        options?: never;
        head?: never;
        /** Rename Application */
        patch: operations["rename_application_applications__external_id__patch"];
        trace?: never;
    };
    "/home": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Home
         * @description Home screen used to poll `/applications` plus journeys/scenarios/
         *     test-suites per application (1+3N calls every tick). One aggregate
         *     query set instead — the cards only ever needed counts, never the items.
         */
        get: operations["get_home_home_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/{external_id}/pause-discovery": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Pause Discovery
         * @description Story 2.17 Task 1 (AC 1).
         */
        post: operations["pause_discovery_applications__external_id__pause_discovery_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/{external_id}/discovery-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Discovery Status */
        get: operations["discovery_status_applications__external_id__discovery_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/{external_id}/resume-discovery": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resume Discovery
         * @description Story 2.17 Task 2 (AC 2/3): starts a fresh `DiscoveryRun` — see
         *     `api.discovery.resume_discovery_run`'s own docstring for why that's the
         *     whole mechanism.
         */
        post: operations["resume_discovery_applications__external_id__resume_discovery_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/discovery-runs/{external_id}/captures": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Captures */
        get: operations["list_captures_discovery_runs__external_id__captures_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/discovery-runs/{external_id}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Discovery Report
         * @description Story 2.22 AC 5: the structured coverage/diagnostics report, queryable
         *     independent of any screen — no `[GAP]` UI exists for this yet (Task 4's
         *     own disclosed scope), so this is the whole surface for now.
         */
        get: operations["get_discovery_report_discovery_runs__external_id__report_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/{external_id}/journeys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Journeys */
        get: operations["list_journeys_applications__external_id__journeys_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/journeys/{external_id}/steps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Journey Steps */
        get: operations["list_journey_steps_journeys__external_id__steps_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/journeys/{external_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Journey */
        delete: operations["delete_journey_journeys__external_id__delete"];
        options?: never;
        head?: never;
        /** Rename Journey */
        patch: operations["rename_journey_journeys__external_id__patch"];
        trace?: never;
    };
    "/applications/{external_id}/test-data": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Test Data Entries */
        get: operations["list_test_data_entries_applications__external_id__test_data_get"];
        put?: never;
        /** Create Test Data Entry */
        post: operations["create_test_data_entry_applications__external_id__test_data_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/test-data/{external_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Test Data Entry */
        delete: operations["delete_test_data_entry_test_data__external_id__delete"];
        options?: never;
        head?: never;
        /** Update Test Data Entry */
        patch: operations["update_test_data_entry_test_data__external_id__patch"];
        trace?: never;
    };
    "/applications/{external_id}/generate-scenarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Scenarios */
        post: operations["generate_scenarios_applications__external_id__generate_scenarios_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/{external_id}/scenarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Scenarios */
        get: operations["list_scenarios_applications__external_id__scenarios_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scenarios/{external_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Scenario */
        delete: operations["delete_scenario_scenarios__external_id__delete"];
        options?: never;
        head?: never;
        /** Rename Scenario */
        patch: operations["rename_scenario_scenarios__external_id__patch"];
        trace?: never;
    };
    "/scenarios/{external_id}/test-data": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Scenario Test Data */
        patch: operations["update_scenario_test_data_scenarios__external_id__test_data_patch"];
        trace?: never;
    };
    "/applications/{external_id}/generate-suite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Suite */
        post: operations["generate_suite_applications__external_id__generate_suite_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/{external_id}/generation-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Generation Status */
        get: operations["generation_status_applications__external_id__generation_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/{external_id}/test-suites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Test Suites */
        get: operations["list_test_suites_applications__external_id__test_suites_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/{external_id}/test-suites/{suite_id}/terminate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Terminate Test Suite
         * @description User-triggered alternative to re-clicking Generate Suite forever
         *     (`generate_suite`'s own comment: a TestSuite left 'incomplete' is
         *     otherwise silently re-triggerable, with no way to just call it done).
         *     Only valid from 'incomplete' — a 'generating' suite is still legitimately
         *     in flight, and a 'complete'/already-'terminated' one has nothing to
         *     terminate.
         */
        post: operations["terminate_test_suite_applications__external_id__test_suites__suite_id__terminate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/{external_id}/test-suites/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Test Suite Project */
        get: operations["download_test_suite_project_applications__external_id__test_suites_download_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/{external_id}/execution-policy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Execution Policy */
        get: operations["get_execution_policy_applications__external_id__execution_policy_get"];
        /**
         * Update Execution Policy
         * @description Upsert — without this, "Run All Tests" has nothing to validate a run
         *     against and can never be clickable (decision from the grill-me design
         *     review). `version` is bumped on every field change, never on a no-op
         *     PUT, so a `TestRun`'s `execution_policy_version` snapshot stays a
         *     meaningful "was this the policy in effect" marker.
         */
        put: operations["update_execution_policy_applications__external_id__execution_policy_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/{external_id}/test-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Test Runs
         * @description Paginated (Application Workspace feature's Runs tab) — every run for
         *     an Application is kept forever (immutable history), so an unpaginated
         *     list would grow without bound.
         */
        get: operations["list_test_runs_applications__external_id__test_runs_get"];
        put?: never;
        /**
         * Trigger Test Run
         * @description No body — every "Run All Tests" click is a fresh, full-scope run
         *     covering every current TestAsset for the application (no rerun-scoped
         *     mode). `PrepareTestRunActivity` creates the actual `TestRun` row
         *     asynchronously, so the very first `GET .../test-runs` poll may briefly
         *     see nothing yet — the same gap `TestSuiteResults.tsx`'s existing poll
         *     loop already tolerates for generation.
         *
         *     ponytail: no `ExecutionPolicy` precondition check here anymore —
         *     removed per explicit request so this never needs setup before it can
         *     be clicked. `GET`/`PUT .../execution-policy` below still exist; nothing
         *     on this path reads them. To restore the original gate: re-add a
         *     `select(ExecutionPolicy)...` lookup and 409 when it's missing (see git
         *     history for the removed version).
         */
        post: operations["trigger_test_run_applications__external_id__test_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/cleanup/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger Cleanup
         * @description Manual purge trigger — same CleanupWorkflow the daily 06:00 IST
         *     Schedule (`api/scripts/create_cleanup_schedule.py`) runs, folded onto
         *     execution-worker's task queue (no dedicated maintenance worker/deployment;
         *     see that worker's registered workflows). Unique per-call id (not the
         *     Schedule's fixed `cleanup-deleted-applications` id) so a manual run never
         *     collides with a same-day scheduled run.
         */
        post: operations["trigger_cleanup_admin_cleanup_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/{external_id}/execution-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Execution Status */
        get: operations["execution_status_applications__external_id__execution_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/{external_id}/test-runs/{test_run_external_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Test Run
         * @description The endpoint the frontend polls while a run is in flight (mirrors
         *     `list_test_suites`'s shape).
         */
        get: operations["get_test_run_applications__external_id__test_runs__test_run_external_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/test-results/{external_id}/artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Test Result Artifacts
         * @description Presigned URLs (mirrors the existing screenshot-URL pattern used
         *     elsewhere in this file) — never proxies the blob itself through this
         *     API.
         */
        get: operations["list_test_result_artifacts_test_results__external_id__artifacts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/{external_id}/test-suite-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Test Suite Status
         * @description Application Workspace's Test Suite tab — one row per current
         *     TestAsset, showing its most recent result (or "not_run" if it's never
         *     been executed) across every TestRun, not just the latest one.
         */
        get: operations["get_test_suite_status_applications__external_id__test_suite_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/test-assets/{external_id}/code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Test Asset Code
         * @description Lazy code fetch for the Suite tab's "View Code" button — keeps the
         *     (large, rarely-viewed) source text out of `get_test_suite_status`'s
         *     paginated rows.
         */
        get: operations["get_test_asset_code_test_assets__external_id__code_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/{external_id}/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Overview
         * @description Application Workspace's Overview tab — one bundled endpoint (health,
         *     stat counts, recent-run trend, latest run, last discovery) rather than
         *     several, mirroring `get_home`'s own "aggregate once, don't reintroduce a
         *     polling waterfall" rationale.
         */
        get: operations["get_overview_applications__external_id__overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Settings */
        get: operations["get_settings_settings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Settings */
        patch: operations["update_settings_settings_patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AcceptInviteRequest */
        AcceptInviteRequest: {
            /** Token */
            token: string;
            /** Name */
            name: string;
            /** Password */
            password: string;
        };
        /** ApplicationCreate */
        ApplicationCreate: {
            /** Name */
            name: string;
            /** Url */
            url: string;
            /**
             * Login Url
             * @description Explicit login page URL, if the login form isn't reachable from the Application URL alone. Optional — omit to let discovery find it itself. Never reachability-checked (a login endpoint can legitimately misbehave without prior session state).
             */
            login_url?: string | null;
            /** Environment */
            environment: string;
            /**
             * Auth Method
             * @default standard_login
             * @enum {string}
             */
            auth_method: "standard_login" | "sso_session_reuse";
            /**
             * Username
             * @description Dedicated Test Account username — not a real end-user identity. Required when auth_method is 'standard_login'.
             */
            username?: string | null;
            /**
             * Password
             * @description Dedicated Test Account password — not a real end-user identity. Required when auth_method is 'standard_login'.
             */
            password?: string | null;
            /**
             * Session State
             * @description A previously-authenticated session the customer already produced (e.g. Playwright storageState.json contents), pasted as-is. Required when auth_method is 'sso_session_reuse'. The platform never performs the SSO/MFA handshake itself — it only reuses a session the customer supplies.
             */
            session_state?: string | null;
        };
        /** ApplicationRead */
        ApplicationRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Url */
            url: string;
            /** Login Url */
            login_url: string | null;
            /** Environment */
            environment: string;
            /**
             * Auth Method
             * @enum {string}
             */
            auth_method: "standard_login" | "sso_session_reuse";
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Discovery Run Id
             * Format: uuid
             */
            discovery_run_id: string;
            /** Discovery Status */
            discovery_status: string;
            /** Discovery Stage */
            discovery_stage: string | null;
            /** Discovery Failure Reason */
            discovery_failure_reason: string | null;
            /** Discovery Coverage Summary */
            discovery_coverage_summary?: {
                [key: string]: number;
            } | null;
        };
        /** ApplicationRenamePayload */
        ApplicationRenamePayload: {
            /** Name */
            name: string;
        };
        /** CaptureRead */
        CaptureRead: {
            /** Kind */
            kind: string;
            /** Summary */
            summary: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ExecutionPolicyRead */
        ExecutionPolicyRead: {
            /** Execution Enabled */
            execution_enabled: boolean;
            /** Allowed Base Urls */
            allowed_base_urls: string[];
            /** Destructive Actions Permitted */
            destructive_actions_permitted: boolean;
            /** Video Capture Enabled */
            video_capture_enabled: boolean;
            /** Version */
            version: number;
        };
        /** ExecutionPolicyUpdate */
        ExecutionPolicyUpdate: {
            /** Execution Enabled */
            execution_enabled?: boolean | null;
            /** Allowed Base Urls */
            allowed_base_urls?: string[] | null;
            /** Destructive Actions Permitted */
            destructive_actions_permitted?: boolean | null;
            /** Video Capture Enabled */
            video_capture_enabled?: boolean | null;
        };
        /** ForgotPasswordRequest */
        ForgotPasswordRequest: {
            /** Email */
            email: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthRead */
        HealthRead: {
            /** Tier */
            tier: string;
            /** Headline */
            headline: string;
        };
        /** HomeApplicationRead */
        HomeApplicationRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Url */
            url: string;
            /** Login Url */
            login_url: string | null;
            /** Environment */
            environment: string;
            /**
             * Auth Method
             * @enum {string}
             */
            auth_method: "standard_login" | "sso_session_reuse";
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Discovery Run Id
             * Format: uuid
             */
            discovery_run_id: string;
            /** Discovery Status */
            discovery_status: string;
            /** Discovery Stage */
            discovery_stage: string | null;
            /** Discovery Failure Reason */
            discovery_failure_reason: string | null;
            /** Discovery Coverage Summary */
            discovery_coverage_summary?: {
                [key: string]: number;
            } | null;
            /** Journey Count */
            journey_count: number;
            /** Scenario Count */
            scenario_count: number;
            /** Scenario Journeys Covered */
            scenario_journeys_covered: number;
            /** Suite Count */
            suite_count: number;
            /** Test Case Count */
            test_case_count: number;
            /** Suites Generating Count */
            suites_generating_count: number;
        };
        /** InviteCreate */
        InviteCreate: {
            /** Email */
            email: string;
            /**
             * Role
             * @default member
             */
            role: string;
        };
        /** InviteRead */
        InviteRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string;
            /** Role */
            role: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
        };
        /** JourneyRead */
        JourneyRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            /** Step Count */
            step_count: number;
        };
        /** JourneyRenamePayload */
        JourneyRenamePayload: {
            /** Name */
            name: string;
        };
        /** JourneyStepRead */
        JourneyStepRead: {
            /** Step Order */
            step_order: number;
            /** Stage Label */
            stage_label: string;
            /** Route */
            route: string;
            /** Method */
            method: string;
            /** Screenshot Url */
            screenshot_url?: string | null;
        };
        /** LatestRunSummaryRead */
        LatestRunSummaryRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Passed Count */
            passed_count: number;
            /** Failed Count */
            failed_count: number;
            /** Blocked Count */
            blocked_count: number;
            /** Duration Ms */
            duration_ms: number | null;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** OverviewRead */
        OverviewRead: {
            health: components["schemas"]["HealthRead"];
            /** Total Tests */
            total_tests: number;
            /** Passed */
            passed: number;
            /** Failed */
            failed: number;
            /** Not Run */
            not_run: number;
            /** Pass Rate */
            pass_rate: number | null;
            /** Trend */
            trend: components["schemas"]["RunTrendPointRead"][];
            latest_run: components["schemas"]["LatestRunSummaryRead"] | null;
            /** Last Discovery Started At */
            last_discovery_started_at: string | null;
        };
        /** ResetPasswordRequest */
        ResetPasswordRequest: {
            /** Token */
            token: string;
            /** Password */
            password: string;
        };
        /** ResetPasswordTarget */
        ResetPasswordTarget: {
            /** Name */
            name: string;
            /** Email */
            email: string;
        };
        /** RunTrendPointRead */
        RunTrendPointRead: {
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /** Pass Rate */
            pass_rate: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ScenarioRead */
        ScenarioRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Journey Id
             * Format: uuid
             */
            journey_id: string;
            /** Journey Name */
            journey_name: string;
            /** Type */
            type: string;
            /** Name */
            name: string;
            /** Steps */
            steps: string[];
            /** Expected Result */
            expected_result: string;
            /** Test Data */
            test_data: components["schemas"]["ScenarioTestDataFieldRead"][];
            /** Test Data Complete */
            test_data_complete: boolean;
        };
        /** ScenarioRenamePayload */
        ScenarioRenamePayload: {
            /** Name */
            name: string;
        };
        /** ScenarioTestDataFieldRead */
        ScenarioTestDataFieldRead: {
            /** Name */
            name: string;
            /** Mandatory */
            mandatory: boolean;
            /** Value */
            value: string | null;
        };
        /** ScenarioTestDataUpdatePayload */
        ScenarioTestDataUpdatePayload: {
            /** Name */
            name: string;
            /** Value */
            value: string;
        };
        /** SettingsRead */
        SettingsRead: {
            /** Max Pages */
            max_pages: number;
            /** Max Discovery Duration Minutes */
            max_discovery_duration_minutes: number;
            /** Navigation Timeout Seconds */
            navigation_timeout_seconds: number;
            /**
             * Interaction Level
             * @enum {string}
             */
            interaction_level: "passive" | "normal" | "aggressive";
            /** Max Journeys */
            max_journeys: number | null;
            /** Max Scenarios Per Journey */
            max_scenarios_per_journey: number | null;
            /** Max Test Cases Per Application */
            max_test_cases_per_application: number | null;
            /**
             * Delete Project After
             * @enum {string}
             */
            delete_project_after: "1_day" | "1_week" | "1_month";
        };
        /** SettingsUpdate */
        SettingsUpdate: {
            /** Max Pages */
            max_pages?: number | null;
            /** Max Discovery Duration Minutes */
            max_discovery_duration_minutes?: number | null;
            /** Navigation Timeout Seconds */
            navigation_timeout_seconds?: number | null;
            /** Interaction Level */
            interaction_level?: ("passive" | "normal" | "aggressive") | null;
            /** Delete Project After */
            delete_project_after?: ("1_day" | "1_week" | "1_month") | null;
            /**
             * Max Journeys
             * @default __unset__
             */
            max_journeys: number | "__unset__" | null;
            /**
             * Max Scenarios Per Journey
             * @default __unset__
             */
            max_scenarios_per_journey: number | "__unset__" | null;
            /**
             * Max Test Cases Per Application
             * @default __unset__
             */
            max_test_cases_per_application: number | "__unset__" | null;
        };
        /** TestAssetCodeRead */
        TestAssetCodeRead: {
            /** Code */
            code: string;
        };
        /** TestAssetStatusPageRead */
        TestAssetStatusPageRead: {
            /** Items */
            items: components["schemas"]["TestAssetStatusRead"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
        };
        /** TestAssetStatusRead */
        TestAssetStatusRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Type */
            type: string;
            /** Steps */
            steps: string[];
            /** Status */
            status: string;
            /** Last Run At */
            last_run_at: string | null;
            /** Duration Ms */
            duration_ms: number | null;
            /** Error Message */
            error_message: string | null;
            /** Latest Test Result Id */
            latest_test_result_id: string | null;
        };
        /** TestCaseRead */
        TestCaseRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Type */
            type: string;
            /** Code */
            code: string;
        };
        /** TestDataEntryCreate */
        TestDataEntryCreate: {
            /** Label */
            label: string;
            /** Field Name */
            field_name: string;
            /**
             * Input Type
             * @default text
             */
            input_type: string;
            /**
             * Route Family
             * @default *
             */
            route_family: string;
            /** Value */
            value: string;
            /**
             * Is Sensitive
             * @default false
             */
            is_sensitive: boolean;
        };
        /** TestDataEntryRead */
        TestDataEntryRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Label */
            label: string;
            /** Normalized Key */
            normalized_key: string;
            /** Is Sensitive */
            is_sensitive: boolean;
            /** Value */
            value: string | null;
        };
        /** TestDataEntryUpdate */
        TestDataEntryUpdate: {
            /** Label */
            label?: string | null;
            /** Value */
            value?: string | null;
            /** Is Sensitive */
            is_sensitive?: boolean | null;
        };
        /** TestResultArtifactRead */
        TestResultArtifactRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Artifact Type */
            artifact_type: string;
            /** Content Type */
            content_type: string;
            /** Size Bytes */
            size_bytes: number;
            /** Url */
            url: string;
        };
        /** TestResultRead */
        TestResultRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Scenario Name */
            scenario_name: string;
            /** Status */
            status: string;
            /** Duration Ms */
            duration_ms: number | null;
            /** Error Message */
            error_message: string | null;
            /** Stack Trace */
            stack_trace: string | null;
            /** Blocked Reason */
            blocked_reason: string | null;
        };
        /** TestRunPageRead */
        TestRunPageRead: {
            /** Items */
            items: components["schemas"]["TestRunRead"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
        };
        /** TestRunRead */
        TestRunRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Status */
            status: string;
            /** Trigger */
            trigger: string;
            /** Pass Rate */
            pass_rate: number | null;
            /** Total Count */
            total_count: number;
            /** Passed Count */
            passed_count: number;
            /** Failed Count */
            failed_count: number;
            /** Timed Out Count */
            timed_out_count: number;
            /** Errored Count */
            errored_count: number;
            /** Blocked Count */
            blocked_count: number;
            /** Blocked Reason */
            blocked_reason: string | null;
            /** Environment Snapshot */
            environment_snapshot: string;
            /** Target Base Url Snapshot */
            target_base_url_snapshot: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Started At */
            started_at: string | null;
            /** Completed At */
            completed_at: string | null;
            /** Results */
            results?: components["schemas"]["TestResultRead"][] | null;
        };
        /** TestSuiteRead */
        TestSuiteRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Journey Name */
            journey_name: string;
            /** Status */
            status: string;
            /** Test Cases */
            test_cases: components["schemas"]["TestCaseRead"][];
        };
        /** UserRead */
        UserRead: {
            /** Name */
            name: string;
            /** Email */
            email: string;
            /** Role */
            role: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    me_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_pending_invites_invites_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InviteRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    send_invite_invites_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InviteCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InviteRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_invite_invites__external_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                external_id: string;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    accept_invite_route_invites_accept_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AcceptInviteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    forgot_password_auth_forgot_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForgotPasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_password_target_auth_reset_password_get: {
        parameters: {
            query: {
                token: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResetPasswordTarget"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_password_route_auth_reset_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_applications_applications_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_application_applications_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplicationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_application_applications__external_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                external_id: string;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_application_applications__external_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                external_id: string;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rename_application_applications__external_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                external_id: string;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplicationRenamePayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_home_home_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HomeApplicationRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pause_discovery_applications__external_id__pause_discovery_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                external_id: string;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    discovery_status_applications__external_id__discovery_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                external_id: string;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: boolean | number;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_discovery_applications__external_id__resume_discovery_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                external_id: string;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_captures_discovery_runs__external_id__captures_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                external_id: string;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaptureRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_discovery_report_discovery_runs__external_id__report_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                external_id: string;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_journeys_applications__external_id__journeys_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                external_id: string;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JourneyRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_journey_steps_journeys__external_id__steps_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                external_id: string;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JourneyStepRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_journey_journeys__external_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                external_id: string;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rename_journey_journeys__external_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                external_id: string;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JourneyRenamePayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JourneyRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_test_data_entries_applications__external_id__test_data_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                external_id: string;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestDataEntryRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_test_data_entry_applications__external_id__test_data_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                external_id: string;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TestDataEntryCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestDataEntryRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_test_data_entry_test_data__external_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                external_id: string;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_test_data_entry_test_data__external_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                external_id: string;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TestDataEntryUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestDataEntryRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_scenarios_applications__external_id__generate_scenarios_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                external_id: string;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: number;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_scenarios_applications__external_id__scenarios_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                external_id: string;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_scenario_scenarios__external_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                external_id: string;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rename_scenario_scenarios__external_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                external_id: string;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScenarioRenamePayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_scenario_test_data_scenarios__external_id__test_data_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                external_id: string;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScenarioTestDataUpdatePayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_suite_applications__external_id__generate_suite_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                external_id: string;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: number;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generation_status_applications__external_id__generation_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                external_id: string;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: boolean;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_test_suites_applications__external_id__test_suites_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                external_id: string;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestSuiteRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    terminate_test_suite_applications__external_id__test_suites__suite_id__terminate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                external_id: string;
                suite_id: string;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestSuiteRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_test_suite_project_applications__external_id__test_suites_download_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                external_id: string;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_execution_policy_applications__external_id__execution_policy_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                external_id: string;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExecutionPolicyRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_execution_policy_applications__external_id__execution_policy_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                external_id: string;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExecutionPolicyUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExecutionPolicyRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_test_runs_applications__external_id__test_runs_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
            };
            header?: never;
            path: {
                external_id: string;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestRunPageRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trigger_test_run_applications__external_id__test_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                external_id: string;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: boolean;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trigger_cleanup_admin_cleanup_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: boolean;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    execution_status_applications__external_id__execution_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                external_id: string;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: boolean;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_test_run_applications__external_id__test_runs__test_run_external_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                external_id: string;
                test_run_external_id: string;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestRunRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_test_result_artifacts_test_results__external_id__artifacts_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                external_id: string;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestResultArtifactRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_test_suite_status_applications__external_id__test_suite_status_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
            };
            header?: never;
            path: {
                external_id: string;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestAssetStatusPageRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_test_asset_code_test_assets__external_id__code_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                external_id: string;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestAssetCodeRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_overview_applications__external_id__overview_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                external_id: string;
            };
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverviewRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_settings_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_settings_settings_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
