"""drop disposable scaffold_probe proof entity

Revision ID: 3206b535a942
Revises: ad5d97c75dc9
Create Date: 2026-07-16 20:30:45.300059

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3206b535a942'
down_revision: str | None = 'ad5d97c75dc9'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scaffold_probe')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'scaffold_probe',
        sa.Column(
            'id', sa.UUID(), server_default=sa.text('uuidv7()'), autoincrement=False, nullable=False
        ),
        sa.Column('note', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            'created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('scaffold_probe_pkey')),
    )
    # ### end Alembic commands ###
