"""add evidence entity

Revision ID: 6c1645fa421a
Revises: c6483d9f0418
Create Date: 2026-07-17 13:24:07.886500

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6c1645fa421a"
down_revision: str | None = "c6483d9f0418"
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "evidence",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("external_id", sa.UUID(), nullable=False),
        sa.Column("discovery_run_id", sa.UUID(), nullable=False),
        sa.Column("journey_id", sa.UUID(), nullable=True),
        sa.Column("type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("object_storage_key", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["discovery_run_id"],
            ["discovery_run.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_evidence_discovery_run_id"), "evidence", ["discovery_run_id"], unique=False
    )
    op.create_index(op.f("ix_evidence_external_id"), "evidence", ["external_id"], unique=True)
    op.create_index(op.f("ix_evidence_journey_id"), "evidence", ["journey_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_evidence_journey_id"), table_name="evidence")
    op.drop_index(op.f("ix_evidence_external_id"), table_name="evidence")
    op.drop_index(op.f("ix_evidence_discovery_run_id"), table_name="evidence")
    op.drop_table("evidence")
    # ### end Alembic commands ###
