"""add failure_reason to discovery_run

Revision ID: a8cdc83f6451
Revises: 6c1645fa421a
Create Date: 2026-07-17 14:28:17.327777

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a8cdc83f6451"
down_revision: str | None = "6c1645fa421a"
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "discovery_run",
        sa.Column("failure_reason", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("discovery_run", "failure_reason")
    # ### end Alembic commands ###
