"""organization platform_user application discovery_run entities

Revision ID: ad5d97c75dc9
Revises: 3a8fcd9d64e0
Create Date: 2026-07-16 19:50:37.609842

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ad5d97c75dc9"
down_revision: str | None = "3a8fcd9d64e0"
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organization",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "application",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("external_id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("environment", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("secret_ref", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organization.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_application_external_id"), "application", ["external_id"], unique=True)
    op.create_index(
        op.f("ix_application_organization_id"), "application", ["organization_id"], unique=False
    )
    op.create_table(
        "platform_user",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("hashed_password", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organization.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_platform_user_email"), "platform_user", ["email"], unique=True)
    op.create_index(
        op.f("ix_platform_user_organization_id"), "platform_user", ["organization_id"], unique=False
    )
    op.create_table(
        "discovery_run",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("external_id", sa.UUID(), nullable=False),
        sa.Column("application_id", sa.UUID(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["application.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_discovery_run_application_id"), "discovery_run", ["application_id"], unique=False
    )
    op.create_index(
        op.f("ix_discovery_run_external_id"), "discovery_run", ["external_id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_discovery_run_external_id"), table_name="discovery_run")
    op.drop_index(op.f("ix_discovery_run_application_id"), table_name="discovery_run")
    op.drop_table("discovery_run")
    op.drop_index(op.f("ix_platform_user_organization_id"), table_name="platform_user")
    op.drop_index(op.f("ix_platform_user_email"), table_name="platform_user")
    op.drop_table("platform_user")
    op.drop_index(op.f("ix_application_organization_id"), table_name="application")
    op.drop_index(op.f("ix_application_external_id"), table_name="application")
    op.drop_table("application")
    op.drop_table("organization")
    # ### end Alembic commands ###
