"""add stop_reason to discovery_run

Revision ID: b1f4d8a2c6e9
Revises: 8d88839005f9
Create Date: 2026-09-10 00:00:00.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b1f4d8a2c6e9"
down_revision: str | None = "8d88839005f9"
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "discovery_run",
        sa.Column("stop_reason", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("discovery_run", "stop_reason")
    # ### end Alembic commands ###
