"""add auth_method to application

Revision ID: c6483d9f0418
Revises: 3206b535a942
Create Date: 2026-07-17 11:48:01.013152

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c6483d9f0418"
down_revision: str | None = "3206b535a942"
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "application",
        sa.Column(
            "auth_method",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
            server_default="standard_login",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("application", "auth_method")
    # ### end Alembic commands ###
