"""add content_score to page

Revision ID: f4a9d3e7c1b8
Revises: e2c8a4f6b9d1
Create Date: 2026-09-25 00:00:00.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f4a9d3e7c1b8"
down_revision: str | None = "e2c8a4f6b9d1"
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("page", sa.Column("content_score", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("page", "content_score")
    # ### end Alembic commands ###
