"""add journey and capability entities

Revision ID: fc7fe4561f07
Revises: a8cdc83f6451
Create Date: 2026-07-17 14:39:12.167081

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fc7fe4561f07"
down_revision: str | None = "a8cdc83f6451"
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "capability",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("external_id", sa.UUID(), nullable=False),
        sa.Column("application_id", sa.UUID(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["application.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_capability_application_id"), "capability", ["application_id"], unique=False
    )
    op.create_index(op.f("ix_capability_external_id"), "capability", ["external_id"], unique=True)
    op.create_table(
        "journey",
        sa.Column("id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column("external_id", sa.UUID(), nullable=False),
        sa.Column("discovery_run_id", sa.UUID(), nullable=False),
        sa.Column("capability_id", sa.UUID(), nullable=True),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("identity_key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["capability_id"],
            ["capability.id"],
        ),
        sa.ForeignKeyConstraint(
            ["discovery_run_id"],
            ["discovery_run.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_journey_capability_id"), "journey", ["capability_id"], unique=False)
    op.create_index(
        op.f("ix_journey_discovery_run_id"), "journey", ["discovery_run_id"], unique=False
    )
    op.create_index(op.f("ix_journey_external_id"), "journey", ["external_id"], unique=True)
    op.create_index(op.f("ix_journey_identity_key"), "journey", ["identity_key"], unique=False)
    op.create_foreign_key(
        "fk_evidence_journey_id_journey", "evidence", "journey", ["journey_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_evidence_journey_id_journey", "evidence", type_="foreignkey")
    op.drop_index(op.f("ix_journey_identity_key"), table_name="journey")
    op.drop_index(op.f("ix_journey_external_id"), table_name="journey")
    op.drop_index(op.f("ix_journey_discovery_run_id"), table_name="journey")
    op.drop_index(op.f("ix_journey_capability_id"), table_name="journey")
    op.drop_table("journey")
    op.drop_index(op.f("ix_capability_external_id"), table_name="capability")
    op.drop_index(op.f("ix_capability_application_id"), table_name="capability")
    op.drop_table("capability")
    # ### end Alembic commands ###
